### PR TITLE
Add preprocessor directives

### PR DESCRIPTION
**Pull request by sebastiencs**
- Structures
- NASM Version
- Date
- Alignement
- few others

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks! Did you have to gather these up manually? Casual searches on the NASM code shows these particular ones as being sprinkled around the code base, unfortunately. For the sake of maintaining these lists into the future, I'm hoping there's a reliable way to get this information in full from future NASM releases.

**Comment by sebastiencs** [comment]
You are welcome. Yes i did it manually.
I just take a look at the NASM code and like you said it's difficult to
extract the information from it.
The only way should be to looking for differences for each version of the
NASM documentation.

By the way, thanks you for this nasm-mode, I was using an old one that
doesn't manage all the instructions.
I would like to contribute more but unfortunately  I don't know the elisp
languages yet.

Sorry for my english,
Sébastien Chapuis.

2015-04-20 5:48 GMT+02:00 Christopher Wellons notifications@github.com:

**Comment by skeeto** [comment]
Alrighty, we'll have to keep a close eye on the changelogs then!

Have you used NASM a lot? Even if you don't know a lot of Elisp yet, it
would definitely be very helpful if, as you make more use of nasm-mode,
you could provide feedback about the mode's auto indentation and the way
NASM syntax is typically formatted. I'm new to NASM specifically (only
used GAS before), I haven't seen a NASM style guide, and I don't even
know where to look yet for a significant, unified body of code written
for NASM as a guide. So I'm still figuring out how nasm-mode could help
direct coding style towards something conventional and idiomatic (how
comments should be formatted, how functions are documented, etc.).

**Comment by sebastiencs** [comment]
I'm coding in assembly language for ~1 year now.
NASM is the only assembler I use and know.
So i'm definitely not the person who can tell you what looks like the NASM style.

But I can tell you a few things from my experience:
- After typing the instruction, is would be nice to indent one more time by typing TAB
        mov[TAB]------rax, rbx
        push[TAB]-----rax
- the macro function of NASM is powerfull, I use it a lot to define function or conditionnal statement.
  In the others nasm-mode, I could add manually instructions and preprocessor macros, they weren't updated so I didn't care to retype my macro and functions in the .el file.
  It would be nice if we could add functions and macros by variables to get the right syntax color. I show you an examble with pseudo code and a .emacs file:

# 

.emacs:
list_macro: "IF", "ELSE", "ENDIF"
list_function: "invoke"

.code:
IF cond
[TAB]------invoke ....
ENDIF

# 

Here, IF, ENDIF and invoke are colored, actually (with your nasm-mode) it's white.
From this code, maybe that indent every time we type [TAB] should be right, but maybe some people won't like.

I hope you will understand what I'm trying to explain.

**Pull request merged**
